/**
 * status codes is used to list and maintain all the possible status codes.
 */

const statusCodes = {
  STATUS_CODE_INVALID_PROMPT: 113,
  STATUS_CODE_SUCCESS: 200,
  STATUS_CODE_SUCCESS_CREATED: 201,
  STATUS_CODE_INVALID_FORMAT: 400,
  STATUS_CODE_UNAUTHORIZED: 401,
  STATUS_CODE_FORBIDDEN: 403,
  STATUS_CODE_DATA_NOT_FOUND: 404,
  STATUS_CODE_FAILURE: 500,
  STATUS_CODE_DATA_SOFT_DELETE: 421,
  STATUS_CODE_VALIDATION_FAILED: 422,
  STATUS_CODE_NOT_ACCEPTABLE: 406,
};

module.exports = {
  statusCodes,
};
